# Generated by Django 4.1.6 on 2023-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('user', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
